import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { CombineProviders } from '@/store/combineProviders';
import { TrendingProvider } from '@/store/trendingStore';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sinopsis web',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CombineProviders providers={[[TrendingProvider, {}]]}>
          {children}
        </CombineProviders>
      </body>
    </html>
  );
}
